# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f2ff26c393f6b63053d99c9b4495929671f044cc555b2c76f3ef4b926a99f79f8fbadb3c59e0b2b1e933c74d3962a0934ed8546b309bf7de97b1b0cbb0702279

test:
  secret_key_base: f9c1c7acce6680c028266643de9d4786385a90d12e0ed55b8dc84e6bb266365b50be9baaa8d055391bcdc98495ef6bb75e06801ada0f095b159d7e6529305ac5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
